#!/usr/bin/env php
<?php

use mon\console\App;

require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/command/Demo.php';
require __DIR__ . '/command/Test.php';
require __DIR__ . '/command/Not.php';
require __DIR__ . '/command/Spin.php';
require __DIR__ . '/command/test/C.php';

$app = new App;

$path = __DIR__ . '/command';
$namspace = 'command';

$app->setTitle('
 _____          _           _____   _       _____ 
/ ____|        (_)         / ____| | |     |_   _|
| |  __   __ _  _   __ _  | |      | |       | |  
| | |_ | / _  || | / _  | | |      | |       | |  
| |__| || (_| || || (_| | | |____  | |____  _| |_ 
\______| \____||_| \____|  \_____| |______||_____|
                                                
');

// 自动加载目录下指令
$app->load($path, $namspace);


$app->run();
