#!/usr/bin/env php
<?php
date_default_timezone_set('PRC');

require __DIR__ . '/../vendor/autoload.php';


// mon\console\libs\Show::write('Test');
// mon\console\libs\Show::write('Test', true, 3);
// mon\console\libs\Show::write('Test', true, true, false);
mon\console\libs\Show::write('Test', false, false, false);
mon\console\libs\Show::write('Demo', true, false);
mon\console\libs\Show::write(['aaaa', 'bbb', 'a' => 'ccc']);


mon\console\libs\Show::block('Hello Block!');
mon\console\libs\Show::block(['ni', 'hao']);

mon\console\libs\Show::splitLine('Test');
mon\console\libs\Show::splitLine();


$data = [
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
];

mon\console\libs\Table::create($data, 'test', ['columns' => ['id', 'A', 'F']]);

$list = [
    'a' => 'aaa',
    'b' => 'bbb',
];

mon\console\libs\Show::dataList([1, 2, 5]);
mon\console\libs\Show::dataList($list);

